Update install composer step

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -23,7 +23,22 @@ jobs:
     steps:
     - uses: actions/checkout@v3
 
-    - uses: ramsey/composer-install@v2
+    - name: Install composer
+      run: |
+        cd /tmp \
+        && EXPECTED_CHECKSUM="$(curl -L "https://composer.github.io/installer.sig")" \
+        && curl -L "https://getcomposer.org/installer" -o composer-setup.php \
+        && ACTUAL_CHECKSUM="$(php -r "echo hash_file('sha384', 'composer-setup.php');")" \
+        && if [ "$EXPECTED_CHECKSUM" != "$ACTUAL_CHECKSUM" ]; then \
+          >&2 echo 'ERROR: Invalid installer checksum'; \
+          rm composer-setup.php; \
+          exit 1; \
+        fi \
+        && php composer-setup.php --quiet \
+        && RESULT=$? \
+        && rm composer-setup.php \
+        && mv /tmp/composer.phar /usr/local/bin/composer \
+        && exit $RESULT
 
     - name: Validate composer.json and composer.lock
       run: composer validate --strict
